set( COMPILER_ROOT /home1/jaeyul.woo/.local/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-)
set( CMAKE_ASM_COMPILER ${COMPILER_ROOT}gcc)
set( CMAKE_C_COMPILER ${COMPILER_ROOT}gcc)
set( CMAKE_LINKER ${COMPILER_ROOT}ld)
set( CMAKE_NM ${COMPILER_ROOT}nm)
set( CMAKE_OBJCOPY ${COMPILER_ROOT}objcopy)
set( CMAKE_OBJDUMP ${COMPILER_ROOT}objdump)
set( COMMON_FLAGS "-march=armv8-m.main -mtune=cortex-m33 -nostdlib -nostdinc -mthumb -g3 -Wno-builtin-declaration-mismatch")
set( CMAKE_ASM_FLAGS "-march=armv8-m.main -mtune=cortex-m33 -nostdlib -nostdinc -mthumb -g3 -Wno-builtin-declaration-mismatch")
set( CMAKE_C_FLAGS "-march=armv8-m.main -mtune=cortex-m33 -nostdlib -nostdinc -mthumb -g3 -Wno-builtin-declaration-mismatch")
set( LINKER_SCRIPT ${CMAKE_HOME_DIRECTORY}/musca-a.lds)
set( CMAKE_EXE_LINKER_FLAGS "-T ${LINKER_SCRIPT} -N -Xlinker -Map=mpu.map")
